name: Pull Masters Data
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      SPORTSDATA_KEY: ${{ secrets.GOLF_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Pull player profiles
        run: node scripts/pullplayers.js

      - name: Run Fetch Script
        run: node update_scores.js

      - name: Commit and Push
        run: 
